name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: |        
        cd .github/
        docker-compose run lms /openedx/requirements/norteamericanoapi/.github/test_lms.sh && docker-compose down -v
        docker-compose run cms /openedx/requirements/norteamericanoapi/.github/test_cms.sh && docker-compose down -v